#!/usr/bin/env python3
"""Regenerate comparison/matrix.md from tests/results/*/scores.json.

Usage: build-matrix.py
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RESULTS = REPO / "tests" / "results"
MATRIX = REPO / "comparison" / "matrix.md"

# Stable row order matches ADR-0001 inventory.
ROW_ORDER = [
    "stephenturner-skill-deslop",
    "blader-humanizer",
    "brandonwise-humanizer",
    "conorbronsdon-avoid-ai-writing",
    "lguz-humanize-writing-skill",
]

COLUMNS = [
    ("pattern_coverage", "Pattern coverage"),
    ("detection_rigor", "Detection rigor"),
    ("voice_calibration", "Voice calibration"),
    ("modes", "Modes"),
    ("convergence", "Convergence"),
    ("ethics_framing", "Ethics framing"),
    ("skill_structure", "Skill structure"),
    ("maturity", "Maturity"),
    ("portability", "Portability"),
    ("conciseness", "Conciseness"),
]

# HTML badge colors for numeric ratings (GitHub markdown renders inline HTML).
BADGE = {
    3: '<sub>🟢 3</sub>',
    2: '<sub>🟡 2</sub>',
    1: '<sub>🔴 1</sub>',
    0: '<sub>⚫ 0</sub>',
}


def load_scores() -> dict:
    scores = {}
    if not RESULTS.is_dir():
        return scores
    for sj in RESULTS.glob("*/scores.json"):
        try:
            data = json.loads(sj.read_text())
            short = data.get("short_name") or sj.parent.name
            scores[short] = data.get("aggregate", {})
        except (json.JSONDecodeError, KeyError):
            continue
    return scores


def cell_html(agg: dict, key: str) -> str:
    c = agg.get(key, {})
    modal = c.get("rating")
    mean = c.get("mean")
    if modal is None or modal == "":
        return ""
    try:
        m = int(modal)
    except (ValueError, TypeError):
        return str(modal)
    badge = BADGE.get(m, str(m))
    if mean is not None and float(mean) != float(m):
        return f"{badge} <sub>({mean})</sub>"
    return badge


def row_sum(agg: dict) -> tuple[int, float]:
    """Return (sum_of_modals, mean_of_means) across all criteria."""
    total = 0
    means = []
    for key, _ in COLUMNS:
        c = agg.get(key, {})
        m = c.get("rating")
        if isinstance(m, (int, float)):
            total += int(m)
        mn = c.get("mean")
        if isinstance(mn, (int, float)):
            means.append(float(mn))
    mean_of_means = round(sum(means) / len(means), 2) if means else 0.0
    return total, mean_of_means


def sum_badge(total: int, max_total: int) -> str:
    pct = total / max_total if max_total else 0
    if pct >= 0.85:
        color = "🟢"
    elif pct >= 0.60:
        color = "🟡"
    else:
        color = "🔴"
    return f"<sub>{color} **{total}**/{max_total}</sub>"


def main() -> int:
    scores = load_scores()
    max_total = len(COLUMNS) * 3

    header = "| Candidate | " + " | ".join(label for _, label in COLUMNS) + " | Sum | Avg |"
    sep = "|---|" + "|".join([":---:" for _ in COLUMNS]) + "|:---:|:---:|"

    lines = [
        "# Comparison Matrix",
        "",
        "Living scoring table. One row per candidate, one column per rubric criterion.",
        "Scoring: **3 = strongest, 1 = weakest, 0 = n/a**. Cells show modal rating with parenthetical mean across fixtures when they differ.",
        "",
        "**Auto-generated by `tests/harness/build-matrix.py` from `tests/results/*/scores.json`.**",
        "Do not edit by hand — run `scripts/run-all.sh` or `tests/harness/build-matrix.py` to regenerate.",
        "",
        "Row order is stable once scored. Column order may change freely.",
        "",
        "## Matrix",
        "",
        header,
        sep,
    ]

    # Build rows sorted by row sum descending (best first)
    ranked = []
    for short in ROW_ORDER:
        agg = scores.get(short, {})
        total, mom = row_sum(agg)
        ranked.append((short, agg, total, mom))
    ranked.sort(key=lambda r: r[2], reverse=True)

    for short, agg, total, mom in ranked:
        cells = [cell_html(agg, key) for key, _ in COLUMNS]
        sb = sum_badge(total, max_total)
        avg = f"<sub>{mom}</sub>" if mom else ""
        lines.append(f"| {short} | " + " | ".join(cells) + f" | {sb} | {avg} |")

    lines.extend([
        "",
        "## Legend",
        "",
        f"- <sub>🟢 3</sub> — strongly meets criterion; best-in-class.",
        f"- <sub>🟡 2</sub> — meets criterion adequately.",
        f"- <sub>🔴 1</sub> — weakly meets or misses criterion.",
        f"- <sub>⚫ 0</sub> — criterion does not apply.",
        "- empty — not yet scored.",
        "- `(x.x)` — mean across the 5 fixtures when it differs from the modal.",
        f"- **Sum** — total of modal ratings (max {max_total}). Rows are sorted by sum, best first.",
        "- **Avg** — mean of per-criterion means across all fixtures and criteria.",
        "",
        "## Notes",
        "",
        "- Scores are auto-generated by an LLM judge. See `tests/harness/` for the harness.",
        "- Decisions citing these scores live in `docs/adr/`.",
        "- Per-candidate verdicts and rationales: `tests/results/<short-name>/scores.json`.",
    ])
    MATRIX.write_text("\n".join(lines) + "\n")
    print(f"wrote {MATRIX}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())