#!/usr/bin/env python3
"""Regenerate comparison/matrix.md from tests/results/*/scores.json.

Usage: build-matrix.py
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RESULTS = REPO / "tests" / "results"
MATRIX = REPO / "comparison" / "matrix.md"

# Stable row order matches ADR-0001 inventory.
ROW_ORDER = [
    "stephenturner-skill-deslop",
    "blader-humanizer",
    "brandonwise-humanizer",
    "conorbronsdon-avoid-ai-writing",
    "lguz-humanize-writing-skill",
]

COLUMNS = [
    ("pattern_coverage", "Pattern coverage"),
    ("detection_rigor", "Detection rigor"),
    ("voice_calibration", "Voice calibration"),
    ("modes", "Modes"),
    ("convergence", "Convergence"),
    ("ethics_framing", "Ethics framing"),
    ("skill_structure", "Skill structure"),
    ("maturity", "Maturity"),
    ("portability", "Portability"),
    ("conciseness", "Conciseness"),
]


def load_scores() -> dict:
    scores = {}
    if not RESULTS.is_dir():
        return scores
    for sj in RESULTS.glob("*/scores.json"):
        try:
            data = json.loads(sj.read_text())
            short = data.get("short_name") or sj.parent.name
            scores[short] = data.get("aggregate", {})
        except (json.JSONDecodeError, KeyError):
            continue
    return scores


def main() -> int:
    scores = load_scores()
    header = "| Candidate | " + " | ".join(label for _, label in COLUMNS) + " |"
    sep = "|---|" + "|".join("---" for _ in COLUMNS) + "|"
    lines = [
        "# Comparison Matrix",
        "",
        "Living scoring table. One row per candidate, one column per rubric criterion.",
        "Scoring: **3 = strongest, 1 = weakest, 0 = n/a**. Cell shows modal rating; parenthetical is mean across fixtures when it differs from the modal.",
        "",
        "**Auto-generated by `tests/harness/build-matrix.py` from `tests/results/*/scores.json`.**",
        "Do not edit by hand — run `scripts/run-all.sh` or `tests/harness/build-matrix.py` to regenerate.",
        "",
        "Row order is stable once scored. Column order may change freely.",
        "",
        "## Matrix",
        "",
        header,
        sep,
    ]
    for short in ROW_ORDER:
        agg = scores.get(short, {})
        cells = []
        for key, _ in COLUMNS:
            c = agg.get(key, {})
            modal = c.get("rating")
            mean = c.get("mean")
            if modal is None or modal == "":
                cells.append("")
                continue
            if mean is not None and mean != modal:
                cells.append(f"{modal} ({mean})")
            else:
                cells.append(f"{modal}")
        lines.append(f"| {short} | " + " | ".join(cells) + " |")

    lines.extend([
        "",
        "## Legend",
        "",
        "- `3` — strongly meets criterion; best-in-class.",
        "- `2` — meets criterion adequately.",
        "- `1` — weakly meets or misses criterion.",
        "- `0` — criterion does not apply.",
        "- empty — not yet scored.",
        "- `N (x.x)` — modal rating with mean across fixtures when they differ.",
        "",
        "## Notes",
        "",
        "- Scores are auto-generated by an LLM judge. See `tests/harness/` for the harness.",
        "- Decisions citing these scores live in `docs/adr/`.",
        "- Per-candidate verdicts and rationales: `tests/results/<short-name>/scores.json`.",
    ])
    MATRIX.write_text("\n".join(lines) + "\n")
    print(f"wrote {MATRIX}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())